services:
  review-manager:
    build: .
    ports: 
      - 8080:8080
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-review-manager}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-you_need_to_change_this}
      POSTGRES_DB: ${POSTGRES_DB:-review-manager}
    restart: unless-stopped
    depends_on:
      postgres_migrate:
        condition: service_completed_successfully
    networks:
      - review-network

  postgres_migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-review-manager}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-you_need_to_change_this}
      POSTGRES_DB: ${POSTGRES_DB:-review-manager}
    entrypoint: ["./migrate"] 
    command: ["up", "-c", "config.yaml"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - review-network

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-review-manager}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-you_need_to_change_this}
      POSTGRES_DB: ${POSTGRES_DB:-review-manager}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-review-manager} -d ${POSTGRES_DB:-review-manager}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - review-network

volumes:
  postgres_data:

networks:
  review-network: